application: inccalender
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css
  secure: optional

- url: /js
  static_dir: js
  secure: optional

- url: /access/.*
  script: access/\1.app
  secure: always

- url: /.*
  script: main.app
  secure: always
