application: inccalender
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /access/.*
  script: access/\1.app

- url: /.*
  script: main.app
